### ISSUE TITLE
XP Rewards

### ISSUE THREAD

**Issue by Labateje** [2mal3/Advancement-Count#19]
Love this datapack! I was wanting to make a datapack that rewards XP based on advancement completion, and this was perfect. I piggy backed off of this and just added "xp add @s # Levels" under each count function. Works like a charm.

Definitely would recommend checking that out!

**Comment by 2mal3** [comment]
Interesting idea and can be implemented well. Let's see ...

**Comment by 2mal3** [comment]
I looked into it, but in my opinion this feature is more or less unnecessary, since many advancements in Minecraft already give Xp anyway. It would just make the whole datapack unnecessarily complex.
