### ISSUE TITLE
Is there a way to connect Advancement Count to "BlazeandCaves Advancement? (more achievements)

### ISSUE THREAD

**Issue by TymekEnderman** [2mal3/Advancement-Count#25]
I mean, if there are more achievements, can the number of points be greater than 214?

Link to datapack: https://modrinth.com/datapack/blazeandcaves-advancements-pack

Thanks for help

**Comment by 2mal3** [comment]
Hi there, I think BlazeandCave's already has a similar option that can be enabled in the settings, so you don't really need Advancement Count for that.
