### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by SirUntouchable** [2mal3/Advancement-Count#26]
Please update this data pack to work in Minecraft 1.21 (along with the 1.21 advancements). I would like to use this on my small SMP server per the request of a couple friends. Would be a nice touch. If this would take a while (like weeks), or is not on your radar of to-do items at all, could you please let me know so I can inform my friends?

Thank you

**Comment by 2mal3** [comment]
Hi, an update is _definitely planned_ and would theoretically be quick. However, the tool I use to automatically build the datapack needs to be updated to 1.21 as well, which has not happened yet. This usually takes a _couple of weeks_ and once the tool is updated an update to Advancement Count is not far off.

**Comment by 2mal3** [comment]
New release is out
