### ISSUE TITLE
Couldn't load tag ...

### ISSUE THREAD

**Issue by BeHaCh** [2mal3/Advancement-Count#27]
### Minecraft version

1.21

### Datapack version

v3.1.3

### Expected Behavior

The datapack would load without errors, and display a score based on advancements.

### Actual Behavior

On load or reloading of datapacks, it displays four errors of "Couldn't load tag ...", and no score is displayed. See attached picture
![image](https://github.com/user-attachments/assets/d2d2bbc5-71f6-40d6-8528-df74413a87cd)

### Reproduction Steps

1) Create a new world
1) Put latest download of Advancement-Count.zip in datapack folder
1) /reload
1) Errors appear

### Additional information

I made sure to test this in a brand new world with no other datapacks or features. I am running a modpack from modrinth, but I doubt that affects this.

**Comment by 2mal3** [comment]
Ooops, thanks.
Minecraft made so many breaking changes to datapacks in 1.21 that my tools couldn't keep up. The problem was with the program that automatically compresses datapack files before releasing them.
An update should be available soon.
